### ISSUE TITLE
LOCALDB_ERROR_INSUFFICIENT_BUFFER

### ISSUE THREAD

**Issue by adcloeshelle** [usis-software/usis.Data.LocalDb#1]
Under what scenarios would you get LOCALDB_ERROR_INSUFFICIENT_BUFFER? We are running into a sporadic issue where calling GetInstances() returns LOCALDB_ERROR_INSUFFICIENT_BUFFER but it is not consistent and we can't figure out the root cause. Any ideas?

**Comment by Udo-usis** [comment]
I've checked the code an tried various situations, but can't provoke the error.
Can you provide more informations about your scenario?

**Comment by adcloeshelle** [comment]
Unfortunately I don't have a ton of info - it is happening randomly on our build machines where we create a lot of Local DBs at the same time. The most interesting piece is it started after we updated our Build VMs, but I'm not sure how that could cause this problem. Any specific information that would be useful?

**Comment by Udo-usis** [comment]
I just committed a change that fixes the issue. You can see the changes in the file "Manager.cs".
It prevents the error by retrying to get the list of instances with a larger buffer, when the count of instances changes between calls due to new instance creation.

**Comment by Udo-usis** [comment]
Fix is available with version 1.1.0 on NuGet.

**Comment by adcloeshelle** [comment]
Very interesting! Were you able to reproduce the issue reliably?

**Comment by Udo-usis** [comment]
Yes, when new instances are created between to call in GetInstances the error is returned.
